name: fitness_app_flutter
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.5
  line_icons: ^2.0.1
  flutter_animation_progress_bar: ^2.0.1
  shared_preferences: ^2.0.7
  numberpicker: ^2.1.1
  appbar_animated: ^0.0.1
  circular_countdown_timer: ^0.2.0
  json_annotation:
  json_serializable:
  http: ^0.13.3
  url_launcher: ^6.0.10
  flutter_tts: ^3.2.2
  fluttertoast: ^8.0.8
  blur: ^3.0.0
  audioplayers: ^0.20.1
  assets_audio_player: ^3.0.3+6
  confetti: ^0.6.0
  intl: ^0.17.0
  font_awesome_flutter: ^9.2.0



dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
